---

- name: Set the grafana agent service status
  ansible.builtin.service:
    name: telemetry
    state: stopped
  when: ansible_facts.services['telemetry.service'] is defined

- name: Remove grafana agent service
  ansible.builtin.file:
    path: /etc/systemd/system/telemetry.service
    state: absent

- name: Reload the SystemD to re-read configurations
  ansible.builtin.systemd:
    daemon-reload: true

- name: Remove agent directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    mode: 0755
  loop: "{{ o11y_grafana_agent_dirs }}"

- name: Remove grafana agent pkg
  ansible.builtin.file:
    path: "{{ o11y_grafana_agent_dir }}"
    state: absent
