---
# Install grafana agents for maas

- name: Set the TCP port for grafana
  ansible.builtin.command: maas $ADMIN maas set-config name=promtail_port value=5238

- name: enable syslog forwarding
  anisible.builtin.command: maas $ADMIN maas set-config name=promtail_enabled value=true

- name: Download and unzip grafana agent
  ansible.builtin.unarchive:
      src: "{{ grafana_agent_pkg }}"
      dest: /opt/agent
      remote_src: true

- name: Make agent executable
  file: dest=/opt/agent/agent-linux-amd64 mode=a+x

- name: Create agent directories
  ansible.builtin.file:
      path: "{{ item.src }}"
      state: directory
      mode: '0755'
  loop:
      - {src: "/var/lib/grafana-agent/positions"}
      - {src: "/var/lib/grafana-agent/wal"}

- name: Copy agent configuration from maas
  ansible.builtin.copy:
      src: /snap/maas/current/usr/share/maas/grafana_agent/agent.yaml.example
      dest: /opt/agent/agent.yml

# TODO: Start the agent: https://discourse.maas.io/t/how-to-set-up-maas-metrics/5204#heading--how-to-export-maas-controller-telemetry
