---
# Installs MAAS from snap

- name: Install "MAAS" from snap
  community.general.snap:
    name: maas
    channel: '{{ maas_version }}'

- name: Install "MAAS-test-db" from snap
  community.general.snap:
    name: maas-test-db
