---
# Installs MAAS

- name: Uninstall MAAS - Snap
  community.general.snap:
    name: maas
    state: absent

- name: Uninstall MAAS - Deb
  ansible.builtin.apt:
    name: "maas-region-api"
    purge: true
    state: absent

- name: Remove MAAS Files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/snap/maas/"
    - "/var/lib/maas/"
    - "/etc/maas/"
