---
# Installs MAAS

- name: Uninstall MAAS - Snap
  community.general.snap:
    name: maas
    state: absent
  when: (maas_installation_type|lower == 'snap')

- name: Uninstall MAAS - Deb
  ansible.builtin.apt:
    pkg:
      - maas
      - maas_region_api
    name: maas
    state: absent
  when: (maas_installation_type|lower == 'deb') and ('maas_rack_controller' in group_names)

- name: Remove regiond.conf
  ansible.builtin.file:
    path: /etc/maas/regiond.conf
    state: absent
  when: maas_installation_type|lower == 'deb'

- name: Remove MAAS Files
  ansible.builtin.file:
    path: "{{ maas_data_dir }}"
    state: absent
