---

# This playbook should deploy everything

- hosts: all
  tasks:
    - name: "Ensure required variables have been defined"
      ansible.builtin.assert:
        quiet: true
        fail_msg: "Required variable has not been defined"
        that:
          - maas_url is defined
          - maas_version is defined
          - maas_installation_type is defined
          - maas_postgres_password is defined

    - name: "Ensure maas_version is a version string"
      ansible.builtin.assert:
        fail_msg: "'{{ maas_version }}' is not a valid version number"
        that:
          - maas_version is regex('\d+\.\d+(\.\d+)?')

    - name: "Ensure o11y can be enabled"
      ansible.builtin.assert:
        quiet: true
        fail_msg: "Prometheus or Loki endpoints must be defined"
        that:
          - (o11y_prometheus_url|length > 0 or o11y_loki_url|length > 0)
      when: o11y_enable

    - name: "Define proxy environment if proxies given"
      ansible.builtin.set_fact:
        proxy_env: "{{ proxy_env | combine({'http_proxy' : http_proxy | d(omit)}) |
          combine({'https_proxy' : https_proxy | d(omit)}) }}"

    - name: "Show proxy environment if in use"
      ansible.builtin.debug:
        msg: "Playbooks using proxy settings: {{ proxy_env }}"
      with_dict: "{{ proxy_env }}"

    - name: "Ensure dist is up to date"
      ansible.builtin.apt:
        upgrade: "dist"
        update_cache: true
        cache_valid_time: 3600
      become: true

- hosts: maas_postgres_primary
  roles:
    - role: maas_postgres_primary
    - role: o11y_agent
  become: true
  gather_facts: true
  tags:
    - maas_postgres_primary
    - maas_postgres
  environment: "{{ proxy_env }}"

- hosts: maas_postgres_secondary
  roles:
    - role: maas_postgres_secondary
    - role: o11y_agent
  become: true
  gather_facts: true
  tags:
    - maas_postgres_secondary
    - maas_postgres
  environment: "{{ proxy_env }}"

# proxies are provisioned prior to rack controllers so the rack controller
# will request to register to region controllers through the proxy
- hosts: maas_proxy
  roles:
    - role: maas_proxy
  become: true
  gather_facts: true
  tags:
    - maas_proxy
  environment: "{{ proxy_env }}"

- hosts: maas_region_controller
  roles:
    - role: maas_region_controller
    - role: o11y_agent
  become: true
  gather_facts: true
  tags:
    - maas_region_controller
    - maas_controller
  environment: "{{ proxy_env }}"

- hosts: maas_rack_controller
  roles:
    - role: maas_rack_controller
    - role: o11y_agent
  become: true
  gather_facts: true
  tags:
    - maas_rack_controller
    - maas_controller
  environment: "{{ proxy_env }}"
