---

# This playbook should deploy everything

- hosts: all
  tasks:
  - name: Fetch MAAS Version if number not given
    ansible.builtin.shell: "\
      set -o pipefail && \
      snap info maas | grep /{{ maas_snap_channel | default('stable') }} | \
      awk -F ' ' '{print $2}' | sort -n | tail -n1 | grep -oP '[0-9]+(.[0-9]+)+'"
    args:
      executable: /bin/bash
    register: maas_tmp_ver
    when: "{{ maas_version is not regex('[0-9]+.[0-9]+(.[0-9]+)?') }}"

  - name: Register valid MAAS version
    ansible.builtin.set_fact:
      maas_use_version: "{{ maas_tmp_ver.stdout | regex_search('[0-9]+.[0-9]+') if maas_version is not regex('[0-9]+.[0-9]+(.[0-9]+)?') else maas_version }}"
      cacheable: true

- hosts: maas_postgres_primary
  roles:
    - role: maas_postgres_primary
  become: true
  gather_facts: true
  tags:
    - maas_postgres_primary
    - maas_postgres

- hosts: maas_postgres_secondary
  roles:
    - role: maas_postgres_secondary
  become: true
  gather_facts: true
  tags:
    - maas_postgres_secondary
    - maas_postgres

# proxies are provisioned prior to rack controllers so the rack controller
# will request to register to region controllers through the proxy
- hosts: maas_proxy
  roles:
    - role: maas_proxy
  become: true
  gather_facts: true
  tags:
    - maas_proxy

- hosts: maas_region_controller
  roles:
    - role: maas_region_controller
  become: true
  gather_facts: true
  tags:
    - maas_region_controller
    - maas_controller

- hosts: maas_rack_controller
  roles:
    - role: maas_rack_controller
  become: true
  gather_facts: true
  tags:
    - maas_rack_controller
    - maas_controller
