---
- name: "Install HAProxy"
  ansible.builtin.apt:
    name: "haproxy"
    state: "{{ 'present' if maas_proxy_state | lower == 'install' else maas_proxy_state }}"

- name: "Stop HAProxy"
  ansible.builtin.systemd:
    name: "haproxy.service"
    state: 'stopped'

- name: "Write HAProxy Config"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: haproxy
    group: haproxy
  notify:
    - "Restart HAProxy"

- name: "Setup firewall"
  ansible.builtin.include_role:
    name: maas_firewall
    tasks_from: setup_firewall_rules
  vars:
    maas_open_tcp_ports:
      - "{{ 5432 if 'maas_postgres' in group_names else (false) }}"
      - "{{ maas_proxy_port }}"
  when: ('maas_region_controller' not in group_names and 'maas_rack_controller' not in group_names)
