---

- name: "Install psycopg2 For Configuration"
  ansible.builtin.pip:
    name: "psycopg2"
    version: "2.9.3"
    state: "present"

- name: "Remove Replication User"
  community.postgresql.postgresql_user:
    name: "{{ maas_postgres_replication_user | default('replicator') }}"
    password: "{{ maas_postgres_replication_password | default('') }}"
    role_attr_flags: replication
    state: absent
  ignore_errors: true

- name: "Remove Replication Slot"
  community.postgresql.postgresql_slot:
    name: "{{ maas_postgres_replication_slot }}"
    db: "maasdb"
    state: absent
  ignore_errors: true

- name: "Uninstall psycopg2"
  ansible.builtin.pip:
    name: "psycopg2"
    version: "2.9.3"
    state: "absent"
