---

- name: "Remove Replication User"
  community.postgresql.postgresql_user:
    name: "{{ maas_postgres_replication_user | default('replicator') }}"
    password: "{{ maas_postgres_replication_password | default('') }}"
    role_attr_flags: replication
    state: absent
  become: true
  become_user: postgres

- name: "Remove Replication Slot"
  community.postgresql.postgresql_slot:
    name: "{{ maas_postgres_replication_slot }}"
    db: "maasdb"
    state: absent
  become: true
  become_user: postgres
