---
# handle TLS setup, config, and enabling

- name: Set default file locations if none given
  ansible.builtin.set_fact:
    tls_key_path: "{{ tls_key_path | default('/etc/ssl/private/maas_tls.pem') }}"
    tls_cert_path: "{{ tls_cert_path | default('/etc/ssl/crt/maas_tls.crt') }}"

- name: Check if a certificate exists
  ansible.builtin.stat:
    path: "{{ tls_cert_path }}"
  register: tls_cert_stat

- name: Check if a key exists
  ansible.builtin.stat:
    path: "{{ tls_key_path }}"
  register: tls_key_stat

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ tls_key_path }}"
  when: generate_tls_cred and not tls_key_stat.stat.exists

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ tls_cert_path }}"
    privatekey_path: "{{ tls_key_path }}"
    provider: selfsigned
  when: generate_tls_cred and not tls_cert_stat.stat.exists

- name: Configure TLS
  ansible.builtin.command: maas config-tls enable {{ tls_key_path }} {{ tls_cert_path }}
  changed_when: false
