---
# handle TLS setup, config, and enabling

- name: Task name
  stat:
    path: "{{ tls_cert_path }}"
  register: tls_cert_stat

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ tls_cert_path }}"
  when: generate_tls_cert && not tls_cert_stat.stat.exists

- name: Configure TLS
  ansible.builtin.command: maas config-tls enable {{ tls_key }} {{ tls_cert_path }}
  # TLS is available only in MAAS 3.2 or higher
  when: maas_version is version("3.2", '>=')