---
- name: "Ensure Pacemaker is started"
  ansible.builtin.systemd:
    name: "pacemaker.service"
    state: started
    enabled: false # if the system is rebooted, the user may not want this member to rejoin automatically
    no_block: false

- name: "Restart sshd"
  ansible.builtin.systemd:
    name: "sshd.service"
    state: restarted
    no_block: false

- name: "Start HA clusters metrics agent"
  ansible.builtin.systemd:
    name: ha_cluster_exporter
    enabled: true
    state: "restarted"
    daemon-reload: true
