---
- name: "Install Corosync"
  ansible.builtin.apt:
    name: "corosync"
    state: present
    update_cache: true

- name: "Write Corosync config"
  ansible.builtin.template:
    src: "corosync.conf.j2"
    dest: "/etc/corosync/corosync.conf"
    mode: 0644
  notify:
    - "Restart Corosync"
