---
# will reset the system state to that prior to maas install
- name: "Uninstall MAAS"
  import_tasks: remove_maas.yaml
  when: "'maas' in ansible_facts.packages"

- name: "Uninstall postgres primary"
  import_tasks: remove_postgres_primary.yaml
  when: "'postgres' in ansible_facts.packages"

- name: "Uninstall postgres secondary"
  import_tasks: remove_postgres_secondary.yaml
  when: "'postgres' in ansible_facts.packages"

- name: "Uninstall postgres"
  import_tasks: remove_postgres.yaml
  when: "'postgres' in ansible_facts.packages"

- name: "Uninstall HAProxy"
  ansible.builtin.apt:
    name: haproxy
    state: absent

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
