---
# Remove everything MAAS related

- name: Uninstall MAAS snap
  community.general.snap:
    name: maas
    state: absent
  when: maas_installation_type|lower == 'snap'

- name: Uninstall MAAS test db snap
  community.general.snap:
    name: "maas-test-db"
    state: absent
  when: "'maas-test-db' in ansible_facts.packages"

- name: Uninstall MAAS from deb
  ansible.builtin.apt:
    name: maas
    state: absent
  when: maas_installation_type|lower == 'deb'

- name: Uninstall deb dependencies
  ansible.builtin.apt:
    name: "maas-region-api"
    state: absent
  when: "'maas-region-api' in ansible_facts.packages"

- name: Uninstall deb dependencies
  ansible.builtin.apt:
    name: "maas-rack-controller"
    state: absent
  when: "'maas-rack-controller' in ansible_facts.packages"
