---
# Remove everything used for postgres

- name: Uninstall pip
  ansible.builtin.apt:
    name: python3-pip
    state: absent
  when: not keep_pip

- name: Uninstall libpq-dev
  ansible.builtin.apt:
    name: libpq-dev
    state: absent

- name: Uninstall psycopg2
  ansible.builtin.pip:
    name: "psycopg2"
    state: absent

- name: Uninstall acl to become postgres user
  ansible.builtin.apt:
    name: acl
    state: absent

- name: Uninstall Postgres Deb"
  ansible.builtin.apt:
    name: "{{ maas_postgres_deb_name }}"
    state: absent
  when: maas_postgres_installation_type|default(maas_installation_type) |lower == 'deb'

- name: Uninstall Postgres Snap"
  community.general.snap:
    name: "{{ maas_postgres_snap_name }}"
    channel: "{{ maas_postgres_snap_track }}/{{ maas_postgres_snap_channel"
    state: absent
  when: maas_postgres_installation_type|default(maas_installation_type) |lower == 'snap'

- name: Delete pg_hba.conf"
  file:
    state: absent
    path: "{{ maas_postgres_config_dir }}pg_hba.conf"

- name: "Delete postgresql.conf"
  file:
    state: absent
    path: "{{ maas_postgres_config_dir }}postgresql.conf"

- name: "Stop Postgres Service"
  ansible.builtin.systemd:
    name: "postgresql@{{ maas_postgres_version_number }}-main.service"
    state: absent
    no_block: no # wait for clean stop
    
- name: "Delete MAAS Postgres Database"
  community.postgresql.postgresql_db:
    name: "maasdb"
    owner: "maas"
    state: absent
  become: true
  become_user: postgres
