---
# Uninstall grafana agents for maas

- name: Remove grafana agent pkg
  ansible.builtin.file:
    path: /opt/agent
    state: absent

- name: Remove agent directories
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: absent
  loop:
    - {src: "/var/lib/grafana-agent/positions"}
    - {src: "/var/lib/grafana-agent/wal"}

- name: Remove the grafana agent
  ansible.builtin.service:
    name: telemetry
    state: stopped
